### ISSUE TITLE
Based on the provided code, there is a potential bug in the send method of the MailChannel class.

### ISSUE THREAD

**Issue by codehacker01** [squareboat/nest-notifications#6]
Based on the provided code, there is a potential bug in the send method of the MailChannel class. The issue lies in the way the notification object is checked for the existence of the toMail property. Let's examine the code and write a bug report:

Bug Report: MailChannel.send() method

Description:
The send method in the MailChannel class is intended to send notifications via email using the Mailman library. However, there is a bug that prevents the method from sending emails when the notification object is expected to have a toMail property.

Bug:
The condition to check if the notification object has the toMail property is incorrect. The current code checks for the presence of the property directly on the notification object using the in operator. This check may lead to unexpected behavior as it does not accurately determine if the property is defined and is a function.

Bug Example:
If notification is an object with a toMail property but the value of that property is not a function, the current code will incorrectly send a NotificationReport with false status, even though it should have been able to send the email notification.

Proposed Fix:
To fix this bug, it is recommended to use the typeof operator to check if the toMail property is indeed a function before proceeding with sending the email notification.

 export class MailChannel extends NotificationChannel {
  async send(
    notifiable: Notifiable,
    notification: NotificationTemplate
  ): Promise<NotificationReport> {
    if (typeof notification['toMail'] !== 'function') {
      return new NotificationReport(false);
    }
      const mailRecipients = notifiable.getMailRecipients();
    const notificationData = await notification['toMail']();
    const { subject, payload, view } = notificationData;
    if (!view) return new NotificationReport(false);
    try {
      await Mailman.init()
        .to(mailRecipients)
        .subject(subject)
        .view(view, payload)
        .send();
       return new NotificationReport(true);
    } catch (err) {
      return new NotificationReport(false);
    }
  }
}

By making the above change, the code will now correctly check if notification['toMail'] is a function before proceeding with the email sending process. If it's not a function, the method will immediately return a NotificationReport with false status, indicating that the notification was not sent.

Note:
Please ensure that the NotificationReport class is appropriately implemented to handle the status of the notification correctly. This bug fix only addresses the issue related to the toMail property check in the MailChannel class.

**Comment by vinayak25** [comment]
Hello @codehacker01, we are no longer maintaining this repository, and instead working on a newer version of this project. We will keep the points you have mentioned in mind.

Thank you for your contribution!
