### ISSUE TITLE
Bug Fix and Revised Code:

### ISSUE THREAD

**Issue by codehacker01** [squareboat/nest-notifications#7]
`Bug` Fix and Revised Code:

The provided code registers the FirebaseModule and MailmanModule asynchronously using the registerAsync method of the NotificationModule. The code could be improved to avoid potential issues with dynamic module registration. Let's make the necessary changes and write the report:

Bug Fixes and Improvements:

The current code has a potential issue with the way the NotificationStorage module is imported and used in the FirebaseModule and MailmanModule. It's better to import and use these modules directly instead of relying on imports inside the registerAsync method.

The FirebaseModule and MailmanModule registrations can be simplified by using their respective registerAsync methods directly, instead of manually creating the providers

**Comment by codehacker01** [comment]
import { Module, DynamicModule, Provider, Type } from '@nestjs/common';
import {
  NotificationOptions,
  NotificationAsyncOptions,
  NotificationAsyncOptionsFactory,
} from './interfaces';
import { NOTIFICATION_OPTIONS } from './constants';
import { NotificationService } from './service';
import { FirebaseModule, FirebaseAsyncOptions } from '@squareboat/nest-firebase';
import { MailmanModule, MailmanAsyncOptions } from '@squareboat/nest-mailman';
import { NotificationStorage } from './storage';

@Module({})
export class NotificationModule {
  /**
   * Register options
   * @param options
   */
  static register(options: NotificationOptions): DynamicModule {
    return {
      global: true,
      module: NotificationModule,
      providers: [
        NotificationService,
        {
          provide: NOTIFICATION_OPTIONS,
          useValue: options,
        },
      ],
    };
  }

  /**
   * Register Async Options for FirebaseModule
   */
  static registerFirebaseAsync(options: FirebaseAsyncOptions): DynamicModule {
    return {
      global: true,
      module: NotificationModule,
      imports: [NotificationStorage],
      providers: [
        {
          provide: FirebaseAsyncOptions,
          useFactory: options.useFactory,
          inject: options.inject || [],
        },
        NotificationService,
      ],
    };
  }

  /**
   * Register Async Options for MailmanModule
   */
  static registerMailmanAsync(options: MailmanAsyncOptions): DynamicModule {
    return {
      global: true,
      module: NotificationModule,
      imports: [NotificationStorage],
      providers: [
        {
          provide: MailmanAsyncOptions,
          useFactory: options.useFactory,
          inject: options.inject || [],
        },
        NotificationService,
      ],
    };
  }

  /**
   * Register Async Options
   */
  static registerAsync(options: NotificationAsyncOptions): DynamicModule {
    if (options.useFactory) {
      return {
        global: true,
        module: NotificationModule,
        providers: [
          {
            provide: NOTIFICATION_OPTIONS,
            useFactory: options.useFactory,
            inject: options.inject || [],
          },
          NotificationService,
        ],
      };
    }

    const inject = [
      (options.useClass || options.useExisting) as Type<NotificationOptions>,
    ];

    return {
      global: true,
      module: NotificationModule,
      imports: [NotificationStorage],
      providers: [
        {
          provide: NOTIFICATION_OPTIONS,
          useFactory: async (optionsFactory: NotificationAsyncOptionsFactory) =>
            await optionsFactory.createNotificationOptions(),
          inject,
        },
        NotificationService,
      ],
    };
  }
}

**Comment by vinayak25** [comment]
Hello @codehacker01, we are no longer maintaining this repository, and instead working on a newer version of this project. We will keep the points you have mentioned in mind. 

Thank you for your contribution!
